name: Mantener Render Activo

on:
  schedule:
    # Cada 5 minutos (UTC)
    - cron: '*/1 * * * *'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a Taskly API
        run: |
          echo "Enviando ping a Taskly backend..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://taskly-clr6.onrender.com/api/ping || echo "error")
          if [ "$response" = "200" ] || [ "$response" = "204" ]; then
            echo "✅ Ping exitoso - Backend activo (código $response)"
          else
            echo "⚠️ Ping fallido - código de respuesta: $response"
          fi
